/**
 * mybookmark - Shared book catalogue
 * Used by both index.html (member dashboard) and admin.html (CRM).
 */

const ECON = {
  revenuePerRentalINR: 43,
  bookLifespanYears: 3
};

const CATALOGUE = [
  // ===== Non-fiction / Self-help / Business =====
  { id: 'b001', title: 'Atomic Habits', author: 'James Clear', genre: 'Self-help', pages: 320, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780735211292-M.jpg', description: 'Tiny changes, remarkable results', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 8 },
  { id: 'b002', title: 'Sapiens', author: 'Yuval Noah Harari', genre: 'History', pages: 464, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062316097-M.jpg', description: 'A brief history of humankind', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 6 },
  { id: 'b003', title: 'The Psychology of Money', author: 'Morgan Housel', genre: 'Finance', pages: 256, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780857197689-M.jpg', description: 'Timeless lessons on wealth, greed, and happiness', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 7 },
  { id: 'b004', title: 'Educated', author: 'Tara Westover', genre: 'Memoir', pages: 352, amazonPrice: 400, coverImage: 'https://covers.openlibrary.org/b/isbn/9780399590504-M.jpg', description: 'A memoir about education, family, and self-invention', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-20', totalRentals: 11 },
  { id: 'b005', title: 'Deep Work', author: 'Cal Newport', genre: 'Productivity', pages: 304, amazonPrice: 400, coverImage: 'https://covers.openlibrary.org/b/isbn/9781455586691-M.jpg', description: 'Rules for focused success in a distracted world', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 5 },
  { id: 'b006', title: 'Outliers', author: 'Malcolm Gladwell', genre: 'Non-fiction', pages: 320, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780316017930-M.jpg', description: 'The story of success', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 4 },
  { id: 'b007', title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson', genre: 'Self-help', pages: 224, amazonPrice: 400, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062457714-M.jpg', description: 'A counterintuitive approach to living a good life', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-25', totalRentals: 6 },
  { id: 'b008', title: 'Zero to One', author: 'Peter Thiel', genre: 'Business', pages: 224, amazonPrice: 400, coverImage: 'https://covers.openlibrary.org/b/isbn/9780804139298-M.jpg', description: 'Notes on startups, or how to build the future', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 3 },
  { id: 'b009', title: 'The Lean Startup', author: 'Eric Ries', genre: 'Business', pages: 336, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307887894-M.jpg', description: 'How constant innovation creates successful businesses', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-10', totalRentals: 10 },
  { id: 'b010', title: 'Think Again', author: 'Adam Grant', genre: 'Non-fiction', pages: 320, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781984878106-M.jpg', description: 'The power of knowing what you don\'t know', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-20', totalRentals: 2 },
  { id: 'b031', title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', genre: 'Psychology', pages: 499, amazonPrice: 499, coverImage: 'https://covers.openlibrary.org/b/isbn/9780374533557-M.jpg', description: 'Two systems that drive the way we think', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 4 },
  { id: 'b032', title: 'Ikigai', author: 'Héctor García & Francesc Miralles', genre: 'Self-help', pages: 208, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780143130727-M.jpg', description: 'The Japanese secret to a long and happy life', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 7 },
  { id: 'b033', title: 'Rich Dad Poor Dad', author: 'Robert Kiyosaki', genre: 'Finance', pages: 336, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781612680194-M.jpg', description: 'What the rich teach their kids about money', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-15', totalRentals: 9 },
  { id: 'b034', title: 'The 7 Habits of Highly Effective People', author: 'Stephen Covey', genre: 'Self-help', pages: 432, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781982137274-M.jpg', description: 'Powerful lessons in personal change', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 5 },
  { id: 'b035', title: 'Start with Why', author: 'Simon Sinek', genre: 'Business', pages: 256, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781591846444-M.jpg', description: 'How great leaders inspire action', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 3 },
  { id: 'b036', title: 'The Power of Now', author: 'Eckhart Tolle', genre: 'Spirituality', pages: 236, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781577314806-M.jpg', description: 'A guide to spiritual enlightenment', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-18', totalRentals: 6 },
  { id: 'b037', title: 'Homo Deus', author: 'Yuval Noah Harari', genre: 'History', pages: 464, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062464316-M.jpg', description: 'A brief history of tomorrow', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 3 },
  { id: 'b038', title: '21 Lessons for the 21st Century', author: 'Yuval Noah Harari', genre: 'Non-fiction', pages: 372, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780525512172-M.jpg', description: 'Navigating life in the face of constant change', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-15', totalRentals: 2 },
  { id: 'b039', title: 'The Hard Thing About Hard Things', author: 'Ben Horowitz', genre: 'Business', pages: 304, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062273208-M.jpg', description: 'Building a business when there are no easy answers', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-20', totalRentals: 2 },
  { id: 'b040', title: 'Grit', author: 'Angela Duckworth', genre: 'Psychology', pages: 352, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781501111105-M.jpg', description: 'The power of passion and perseverance', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 3 },
  { id: 'b041', title: 'Quiet', author: 'Susan Cain', genre: 'Psychology', pages: 352, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307352156-M.jpg', description: 'The power of introverts in a world that can\'t stop talking', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-25', totalRentals: 4 },
  { id: 'b042', title: 'Shoe Dog', author: 'Phil Knight', genre: 'Memoir', pages: 400, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781501135910-M.jpg', description: 'A memoir by the creator of Nike', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 4 },
  { id: 'b043', title: 'The Monk Who Sold His Ferrari', author: 'Robin Sharma', genre: 'Self-help', pages: 198, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062515674-M.jpg', description: 'A fable about fulfilling your dreams', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-20', totalRentals: 8 },
  { id: 'b044', title: 'The Courage to Be Disliked', author: 'Ichiro Kishimi & Fumitake Koga', genre: 'Psychology', pages: 288, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781501197277-M.jpg', description: 'How to free yourself and achieve real happiness', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-12', totalRentals: 2 },
  { id: 'b045', title: 'Can\'t Hurt Me', author: 'David Goggins', genre: 'Memoir', pages: 364, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781544512280-M.jpg', description: 'Master your mind and defy the odds', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 3 },
  { id: 'b046', title: 'Man\'s Search for Meaning', author: 'Viktor Frankl', genre: 'Psychology', pages: 184, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9780807014295-M.jpg', description: 'Finding purpose in suffering', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 6 },
  { id: 'b047', title: 'Meditations', author: 'Marcus Aurelius', genre: 'Philosophy', pages: 256, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780140449334-M.jpg', description: 'Stoic wisdom from a Roman emperor', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 5 },
  { id: 'b048', title: 'The Almanack of Naval Ravikant', author: 'Eric Jorgenson', genre: 'Self-help', pages: 242, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781544514215-M.jpg', description: 'A guide to wealth and happiness', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 5 },
  { id: 'b049', title: 'Influence', author: 'Robert Cialdini', genre: 'Psychology', pages: 336, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062937650-M.jpg', description: 'The psychology of persuasion', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-18', totalRentals: 2 },
  { id: 'b050', title: 'Range', author: 'David Epstein', genre: 'Non-fiction', pages: 352, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780735214484-M.jpg', description: 'Why generalists triumph in a specialized world', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-20', totalRentals: 2 },
  { id: 'b051', title: 'Factfulness', author: 'Hans Rosling', genre: 'Non-fiction', pages: 352, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781250107817-M.jpg', description: 'Ten reasons we\'re wrong about the world', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-15', totalRentals: 2 },
  { id: 'b052', title: 'Talking to Strangers', author: 'Malcolm Gladwell', genre: 'Non-fiction', pages: 400, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780316478526-M.jpg', description: 'What we should know about the people we don\'t know', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-08', totalRentals: 3 },
  { id: 'b053', title: 'Rework', author: 'Jason Fried & DHH', genre: 'Business', pages: 288, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307463746-M.jpg', description: 'A better, faster, easier way to succeed in business', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-12', totalRentals: 2 },
  { id: 'b054', title: 'The $100 Startup', author: 'Chris Guillebeau', genre: 'Business', pages: 304, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307951526-M.jpg', description: 'Reinvent the way you make a living', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 3 },
  { id: 'b055', title: 'The 4-Hour Work Week', author: 'Tim Ferriss', genre: 'Business', pages: 416, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307465351-M.jpg', description: 'Escape 9-5, live anywhere, and join the new rich', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-28', totalRentals: 4 },
  { id: 'b056', title: 'Mindset', author: 'Carol Dweck', genre: 'Psychology', pages: 320, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780345472328-M.jpg', description: 'The new psychology of success', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 3 },
  { id: 'b057', title: 'Stuff: Compulsive Hoarding', author: 'Randy Frost', genre: 'Psychology', pages: 304, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780547422558-M.jpg', description: 'Understanding the lives of compulsive hoarders', popularity: 3, expectedAnnualRentals: 8, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-15', totalRentals: 1 },
  { id: 'b058', title: 'Good to Great', author: 'Jim Collins', genre: 'Business', pages: 320, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780066620992-M.jpg', description: 'Why some companies make the leap and others don\'t', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 4 },

  // ===== Fiction / Literary =====
  { id: 'b011', title: 'The Midnight Library', author: 'Matt Haig', genre: 'Fiction', pages: 304, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780525559474-M.jpg', description: 'Between life and death, there is a library', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 7 },
  { id: 'b012', title: 'The Alchemist', author: 'Paulo Coelho', genre: 'Fiction', pages: 192, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062315007-M.jpg', description: 'A shepherd\'s journey to find his treasure', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 12 },
  { id: 'b013', title: 'The God of Small Things', author: 'Arundhati Roy', genre: 'Literary fiction', pages: 340, amazonPrice: 400, coverImage: 'https://covers.openlibrary.org/b/isbn/9780679457312-M.jpg', description: 'Booker Prize-winning Indian novel', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 5 },
  { id: 'b014', title: 'The White Tiger', author: 'Aravind Adiga', genre: 'Literary fiction', pages: 320, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781416562603-M.jpg', description: 'Booker Prize-winning dark satire of modern India', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-12', totalRentals: 4 },
  { id: 'b015', title: '1984', author: 'George Orwell', genre: 'Classic', pages: 328, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780451524935-M.jpg', description: 'A dystopian masterpiece', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-15', totalRentals: 8 },
  { id: 'b016', title: 'To Kill a Mockingbird', author: 'Harper Lee', genre: 'Classic', pages: 336, amazonPrice: 300, coverImage: 'https://covers.openlibrary.org/b/isbn/9780060935467-M.jpg', description: 'A Pulitzer Prize-winning novel of justice and childhood', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-20', totalRentals: 6 },
  { id: 'b017', title: 'The Namesake', author: 'Jhumpa Lahiri', genre: 'Fiction', pages: 304, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780618485222-M.jpg', description: 'An Indian-American family saga', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-18', totalRentals: 5 },
  { id: 'b018', title: 'A Fine Balance', author: 'Rohinton Mistry', genre: 'Literary fiction', pages: 624, amazonPrice: 500, coverImage: 'https://covers.openlibrary.org/b/isbn/9781400030651-M.jpg', description: 'Set during India\'s Emergency', popularity: 3, expectedAnnualRentals: 8, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-05', totalRentals: 3 },
  { id: 'b059', title: 'The Kite Runner', author: 'Khaled Hosseini', genre: 'Fiction', pages: 371, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781594631931-M.jpg', description: 'A haunting tale of friendship and redemption', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-05', totalRentals: 6 },
  { id: 'b060', title: 'A Thousand Splendid Suns', author: 'Khaled Hosseini', genre: 'Fiction', pages: 372, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781594489501-M.jpg', description: 'Two women in war-torn Afghanistan', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 5 },
  { id: 'b061', title: 'Normal People', author: 'Sally Rooney', genre: 'Fiction', pages: 266, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781984822178-M.jpg', description: 'A complex love story of two Irish teens', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 3 },
  { id: 'b062', title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', genre: 'Classic', pages: 180, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780743273565-M.jpg', description: 'The American Dream in the Jazz Age', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-10', totalRentals: 7 },
  { id: 'b063', title: 'Pride and Prejudice', author: 'Jane Austen', genre: 'Classic', pages: 432, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780141439518-M.jpg', description: 'The ultimate romance novel', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-18', totalRentals: 6 },
  { id: 'b064', title: 'Brave New World', author: 'Aldous Huxley', genre: 'Classic', pages: 288, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780060850524-M.jpg', description: 'A chilling dystopia of engineered happiness', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-01', totalRentals: 4 },
  { id: 'b065', title: 'Animal Farm', author: 'George Orwell', genre: 'Classic', pages: 141, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780451526342-M.jpg', description: 'A political allegory about power and corruption', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-12', totalRentals: 7 },
  { id: 'b066', title: 'The Catcher in the Rye', author: 'JD Salinger', genre: 'Classic', pages: 277, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9780316769488-M.jpg', description: 'Coming of age in post-war America', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-25', totalRentals: 5 },
  { id: 'b067', title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', genre: 'Literary fiction', pages: 417, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780060883287-M.jpg', description: 'Seven generations of the Buendía family', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-08', totalRentals: 4 },
  { id: 'b068', title: 'The Book Thief', author: 'Markus Zusak', genre: 'Fiction', pages: 584, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780375842207-M.jpg', description: 'A story narrated by Death during WWII', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 5 },
  { id: 'b069', title: 'Shantaram', author: 'Gregory David Roberts', genre: 'Fiction', pages: 936, amazonPrice: 500, coverImage: 'https://covers.openlibrary.org/b/isbn/9780312330521-M.jpg', description: 'An epic set in the Bombay underworld', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 3 },
  { id: 'b070', title: 'The Palace of Illusions', author: 'Chitra Banerjee Divakaruni', genre: 'Fiction', pages: 360, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780385515993-M.jpg', description: 'The Mahabharata retold by Draupadi', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-25', totalRentals: 4 },
  { id: 'b071', title: 'Five Point Someone', author: 'Chetan Bhagat', genre: 'Fiction', pages: 270, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9788129135490-M.jpg', description: 'What not to do at IIT', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-20', totalRentals: 8 },
  { id: 'b072', title: 'The Immortals of Meluha', author: 'Amish Tripathi', genre: 'Fiction', pages: 400, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9789380658742-M.jpg', description: 'Shiva reimagined as a man', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-25', totalRentals: 7 },
  { id: 'b073', title: 'Train to Pakistan', author: 'Khushwant Singh', genre: 'Literary fiction', pages: 181, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780802130792-M.jpg', description: 'Partition through the eyes of a border village', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-05', totalRentals: 5 },
  { id: 'b074', title: 'The Guide', author: 'RK Narayan', genre: 'Literary fiction', pages: 220, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780140185379-M.jpg', description: 'A con man becomes a holy man in Malgudi', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-30', totalRentals: 5 },
  { id: 'b075', title: 'Malgudi Days', author: 'RK Narayan', genre: 'Fiction', pages: 256, amazonPrice: 199, coverImage: 'https://covers.openlibrary.org/b/isbn/9780140185430-M.jpg', description: 'Short stories from the fictional town of Malgudi', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-02', totalRentals: 4 },
  { id: 'b076', title: 'Tuesdays with Morrie', author: 'Mitch Albom', genre: 'Fiction', pages: 192, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9780767905923-M.jpg', description: 'An old man, a young man, and life\'s greatest lesson', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-12', totalRentals: 6 },
  { id: 'b077', title: 'The Five People You Meet in Heaven', author: 'Mitch Albom', genre: 'Fiction', pages: 196, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9780786868716-M.jpg', description: 'What happens after we die', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-18', totalRentals: 4 },
  { id: 'b078', title: 'Life of Pi', author: 'Yann Martel', genre: 'Fiction', pages: 326, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780156027328-M.jpg', description: 'A boy, a tiger, and the Pacific Ocean', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-22', totalRentals: 5 },
  { id: 'b079', title: 'Where the Crawdads Sing', author: 'Delia Owens', genre: 'Fiction', pages: 384, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780735219090-M.jpg', description: 'A murder mystery and coming-of-age tale', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 3 },
  { id: 'b080', title: 'It Ends with Us', author: 'Colleen Hoover', genre: 'Fiction', pages: 384, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781501110368-M.jpg', description: 'A brave and heartbreaking romance', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 4 },
  { id: 'b081', title: 'Verity', author: 'Colleen Hoover', genre: 'Thriller', pages: 314, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781538724736-M.jpg', description: 'A bone-chilling thriller', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-08', totalRentals: 3 },

  // ===== Memoir / Biography =====
  { id: 'b019', title: 'Wings of Fire', author: 'APJ Abdul Kalam', genre: 'Biography', pages: 180, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9788173711466-M.jpg', description: 'Autobiography of India\'s missile man', popularity: 4, expectedAnnualRentals: 15, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-08', totalRentals: 9 },
  { id: 'b020', title: 'Born a Crime', author: 'Trevor Noah', genre: 'Memoir', pages: 304, amazonPrice: 400, coverImage: 'https://covers.openlibrary.org/b/isbn/9780399588174-M.jpg', description: 'Stories from a South African childhood', popularity: 4, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-22', totalRentals: 6 },
  { id: 'b021', title: 'When Breath Becomes Air', author: 'Paul Kalanithi', genre: 'Memoir', pages: 256, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780812988406-M.jpg', description: 'A neurosurgeon faces his own mortality', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 7 },
  { id: 'b022', title: 'Becoming', author: 'Michelle Obama', genre: 'Memoir', pages: 448, amazonPrice: 500, coverImage: 'https://covers.openlibrary.org/b/isbn/9781524763138-M.jpg', description: 'Michelle Obama\'s memoir', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 3 },
  { id: 'b082', title: 'Steve Jobs', author: 'Walter Isaacson', genre: 'Biography', pages: 656, amazonPrice: 599, coverImage: 'https://covers.openlibrary.org/b/isbn/9781451648539-M.jpg', description: 'The exclusive biography of Apple\'s visionary', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-28', totalRentals: 4 },
  { id: 'b083', title: 'Elon Musk', author: 'Walter Isaacson', genre: 'Biography', pages: 688, amazonPrice: 699, coverImage: 'https://covers.openlibrary.org/b/isbn/9781982181284-M.jpg', description: 'The life of the world\'s most polarizing entrepreneur', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 2 },
  { id: 'b084', title: 'The Diary of a Young Girl', author: 'Anne Frank', genre: 'Memoir', pages: 283, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780553296983-M.jpg', description: 'Anne Frank\'s diary from the Holocaust', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-15', totalRentals: 6 },
  { id: 'b085', title: 'Long Walk to Freedom', author: 'Nelson Mandela', genre: 'Biography', pages: 656, amazonPrice: 500, coverImage: 'https://covers.openlibrary.org/b/isbn/9780316548182-M.jpg', description: 'Nelson Mandela\'s autobiography', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 4 },
  { id: 'b086', title: 'An Autobiography: My Experiments with Truth', author: 'Mahatma Gandhi', genre: 'Biography', pages: 480, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780486245935-M.jpg', description: 'Gandhi\'s own account of his life', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-20', totalRentals: 5 },
  { id: 'b087', title: 'Greenlights', author: 'Matthew McConaughey', genre: 'Memoir', pages: 304, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780593139134-M.jpg', description: 'An unconventional memoir from the actor', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-12', totalRentals: 2 },

  // ===== Sci-fi / Thriller / Mystery =====
  { id: 'b023', title: 'Project Hail Mary', author: 'Andy Weir', genre: 'Sci-fi', pages: 480, amazonPrice: 500, coverImage: 'https://covers.openlibrary.org/b/isbn/9780593135204-M.jpg', description: 'A lone astronaut on a mission to save Earth', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-15', totalRentals: 2 },
  { id: 'b024', title: 'Dune', author: 'Frank Herbert', genre: 'Sci-fi', pages: 688, amazonPrice: 500, coverImage: 'https://covers.openlibrary.org/b/isbn/9780441172719-M.jpg', description: 'Epic space opera on the desert planet of Arrakis', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 4 },
  { id: 'b025', title: 'Gone Girl', author: 'Gillian Flynn', genre: 'Thriller', pages: 432, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307588371-M.jpg', description: 'A psychological thriller about a missing wife', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 5 },
  { id: 'b026', title: 'The Silent Patient', author: 'Alex Michaelides', genre: 'Thriller', pages: 336, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781250301697-M.jpg', description: 'A shocking psychological thriller', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-28', totalRentals: 4 },
  { id: 'b088', title: 'The Martian', author: 'Andy Weir', genre: 'Sci-fi', pages: 369, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780553418026-M.jpg', description: 'One man stranded on Mars', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 5 },
  { id: 'b089', title: 'The Girl on the Train', author: 'Paula Hawkins', genre: 'Thriller', pages: 336, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9781594634024-M.jpg', description: 'A psychological thriller about obsession', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 5 },
  { id: 'b090', title: 'The Da Vinci Code', author: 'Dan Brown', genre: 'Thriller', pages: 597, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307474278-M.jpg', description: 'A murder in the Louvre leads to an ancient secret', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-10', totalRentals: 8 },
  { id: 'b091', title: 'Angels & Demons', author: 'Dan Brown', genre: 'Thriller', pages: 616, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781416524793-M.jpg', description: 'A symbologist races against time at the Vatican', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-15', totalRentals: 6 },
  { id: 'b092', title: 'Hitchhiker\'s Guide to the Galaxy', author: 'Douglas Adams', genre: 'Sci-fi', pages: 224, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9780345391803-M.jpg', description: 'Don\'t panic - and always carry a towel', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-08', totalRentals: 5 },
  { id: 'b093', title: 'And Then There Were None', author: 'Agatha Christie', genre: 'Mystery', pages: 272, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062073488-M.jpg', description: 'Ten strangers, one island, no escape', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-25', totalRentals: 6 },
  { id: 'b094', title: 'Murder on the Orient Express', author: 'Agatha Christie', genre: 'Mystery', pages: 274, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062073501-M.jpg', description: 'Poirot solves a murder on a snowbound train', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-01', totalRentals: 5 },
  { id: 'b095', title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', genre: 'Thriller', pages: 672, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780307454546-M.jpg', description: 'A journalist and a hacker uncover dark secrets', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-18', totalRentals: 4 },
  { id: 'b096', title: 'Dark Matter', author: 'Blake Crouch', genre: 'Sci-fi', pages: 342, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781101904220-M.jpg', description: 'A mind-bending multiverse thriller', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 3 },
  { id: 'b097', title: 'Recursion', author: 'Blake Crouch', genre: 'Sci-fi', pages: 320, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9781524759780-M.jpg', description: 'Memory is the ultimate weapon', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 2 },

  // ===== Kids / Young Adult =====
  { id: 'b027', title: 'Wonder', author: 'RJ Palacio', genre: 'YA', pages: 320, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780375869020-M.jpg', description: 'About a boy with a facial difference starting school', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 6 },
  { id: 'b028', title: 'Charlie and the Chocolate Factory', author: 'Roald Dahl', genre: 'Kids', pages: 176, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780142410318-M.jpg', description: 'A classic kids\' story of magic and chocolate', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-12', totalRentals: 11 },
  { id: 'b029', title: 'Percy Jackson: The Lightning Thief', author: 'Rick Riordan', genre: 'YA', pages: 384, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780786838653-M.jpg', description: 'Greek mythology meets modern teen adventure', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-08', totalRentals: 7 },
  { id: 'b030', title: 'The Little Prince', author: 'Antoine de Saint-Exupéry', genre: 'All-ages', pages: 96, amazonPrice: 200, coverImage: 'https://covers.openlibrary.org/b/isbn/9780156012195-M.jpg', description: 'A timeless tale of friendship and wonder', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-25', totalRentals: 8 },
  { id: 'b098', title: 'Harry Potter and the Philosopher\'s Stone', author: 'JK Rowling', genre: 'YA', pages: 332, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747532743-M.jpg', description: 'The boy who lived', popularity: 5, expectedAnnualRentals: 24, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 12 },
  { id: 'b099', title: 'Harry Potter and the Chamber of Secrets', author: 'JK Rowling', genre: 'YA', pages: 360, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747538486-M.jpg', description: 'The Chamber of Secrets has been opened', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 10 },
  { id: 'b100', title: 'Harry Potter and the Prisoner of Azkaban', author: 'JK Rowling', genre: 'YA', pages: 468, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747546290-M.jpg', description: 'A dangerous prisoner has escaped', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 10 },
  { id: 'b101', title: 'Harry Potter and the Goblet of Fire', author: 'JK Rowling', genre: 'YA', pages: 636, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747546245-M.jpg', description: 'The Triwizard Tournament begins', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 9 },
  { id: 'b102', title: 'Harry Potter and the Order of the Phoenix', author: 'JK Rowling', genre: 'YA', pages: 870, amazonPrice: 499, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747569404-M.jpg', description: 'The Order fights back', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 8 },
  { id: 'b103', title: 'Harry Potter and the Half-Blood Prince', author: 'JK Rowling', genre: 'YA', pages: 652, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747581086-M.jpg', description: 'The Half-Blood Prince\'s secrets', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 8 },
  { id: 'b104', title: 'Harry Potter and the Deathly Hallows', author: 'JK Rowling', genre: 'YA', pages: 759, amazonPrice: 499, coverImage: 'https://covers.openlibrary.org/b/isbn/9780747591054-M.jpg', description: 'The final battle', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-05', totalRentals: 8 },
  { id: 'b105', title: 'Matilda', author: 'Roald Dahl', genre: 'Kids', pages: 240, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780142410370-M.jpg', description: 'A genius girl takes on her terrible parents', popularity: 5, expectedAnnualRentals: 20, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-15', totalRentals: 9 },
  { id: 'b106', title: 'James and the Giant Peach', author: 'Roald Dahl', genre: 'Kids', pages: 160, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780142410363-M.jpg', description: 'A magical adventure inside a giant peach', popularity: 4, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-18', totalRentals: 7 },
  { id: 'b107', title: 'The BFG', author: 'Roald Dahl', genre: 'Kids', pages: 208, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780142410387-M.jpg', description: 'The Big Friendly Giant catches dreams', popularity: 4, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-20', totalRentals: 7 },
  { id: 'b108', title: 'Charlotte\'s Web', author: 'EB White', genre: 'Kids', pages: 192, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9780064400558-M.jpg', description: 'A spider saves a pig\'s life', popularity: 4, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-22', totalRentals: 6 },
  { id: 'b109', title: 'Diary of a Wimpy Kid', author: 'Jeff Kinney', genre: 'Kids', pages: 217, amazonPrice: 299, coverImage: 'https://covers.openlibrary.org/b/isbn/9780810993136-M.jpg', description: 'Greg Heffley\'s hilarious middle school diary', popularity: 5, expectedAnnualRentals: 22, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-01-08', totalRentals: 10 },
  { id: 'b110', title: 'The Hunger Games', author: 'Suzanne Collins', genre: 'YA', pages: 374, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780439023481-M.jpg', description: 'A fight for survival in a dystopian arena', popularity: 5, expectedAnnualRentals: 18, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-01', totalRentals: 7 },
  { id: 'b111', title: 'The Fault in Our Stars', author: 'John Green', genre: 'YA', pages: 318, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780525478812-M.jpg', description: 'Two teens with cancer fall in love', popularity: 5, expectedAnnualRentals: 16, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-05', totalRentals: 6 },
  { id: 'b112', title: 'Divergent', author: 'Veronica Roth', genre: 'YA', pages: 487, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780062024022-M.jpg', description: 'One choice can transform you', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-10', totalRentals: 5 },
  { id: 'b113', title: 'The Maze Runner', author: 'James Dashner', genre: 'YA', pages: 384, amazonPrice: 350, coverImage: 'https://covers.openlibrary.org/b/isbn/9780385737951-M.jpg', description: 'Trapped in a maze with no memory', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-12', totalRentals: 5 },

  // ===== Health / Science / Misc =====
  { id: 'b114', title: 'Why We Sleep', author: 'Matthew Walker', genre: 'Science', pages: 368, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781501144318-M.jpg', description: 'The new science of sleep and dreams', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-01', totalRentals: 3 },
  { id: 'b115', title: 'A Brief History of Time', author: 'Stephen Hawking', genre: 'Science', pages: 256, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780553380163-M.jpg', description: 'From the Big Bang to black holes', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-05', totalRentals: 5 },
  { id: 'b116', title: 'The Selfish Gene', author: 'Richard Dawkins', genre: 'Science', pages: 360, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9780199291151-M.jpg', description: 'Evolution from the gene\'s perspective', popularity: 3, expectedAnnualRentals: 8, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-20', totalRentals: 3 },
  { id: 'b117', title: 'Eat That Frog!', author: 'Brian Tracy', genre: 'Productivity', pages: 144, amazonPrice: 250, coverImage: 'https://covers.openlibrary.org/b/isbn/9781576754221-M.jpg', description: '21 ways to stop procrastinating', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-05', totalRentals: 3 },
  { id: 'b118', title: 'The Power of Habit', author: 'Charles Duhigg', genre: 'Psychology', pages: 400, amazonPrice: 450, coverImage: 'https://covers.openlibrary.org/b/isbn/9781400069286-M.jpg', description: 'Why we do what we do in life and business', popularity: 4, expectedAnnualRentals: 14, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-15', totalRentals: 5 },
  { id: 'b119', title: 'Freakonomics', author: 'Steven Levitt & Stephen Dubner', genre: 'Non-fiction', pages: 320, amazonPrice: 399, coverImage: 'https://covers.openlibrary.org/b/isbn/9780060731335-M.jpg', description: 'A rogue economist explores the hidden side of everything', popularity: 4, expectedAnnualRentals: 12, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-02-25', totalRentals: 4 },
  { id: 'b120', title: 'Guns, Germs, and Steel', author: 'Jared Diamond', genre: 'History', pages: 528, amazonPrice: 499, coverImage: 'https://covers.openlibrary.org/b/isbn/9780393317558-M.jpg', description: 'The fates of human societies', popularity: 4, expectedAnnualRentals: 10, status: 'available', condition: 'good', currentBorrower: null, dateAcquired: '2026-03-10', totalRentals: 2 },
];

function bookEconomics(book) {
  const annualRevenue = book.expectedAnnualRentals * ECON.revenuePerRentalINR;
  const year1Profit = annualRevenue - book.amazonPrice;
  const year1ROI = Math.round((annualRevenue / book.amazonPrice) * 100);
  const paybackMonths = annualRevenue > 0 ? Math.round((book.amazonPrice / annualRevenue) * 12) : null;
  const lifetimeRevenue = annualRevenue * ECON.bookLifespanYears;
  const lifetimeProfit = lifetimeRevenue - book.amazonPrice;
  return { annualRevenue, year1Profit, year1ROI, paybackMonths, lifetimeRevenue, lifetimeProfit };
}

function catalogueMetrics(books = CATALOGUE) {
  let totalInventoryCost = 0;
  let totalAnnualRevenue = 0;
  let availableCount = 0;
  let checkedOutCount = 0;
  let damagedCount = 0;
  for (const b of books) {
    totalInventoryCost += b.amazonPrice;
    totalAnnualRevenue += bookEconomics(b).annualRevenue;
    if (b.status === 'available') availableCount++;
    else if (b.status === 'checked-out') checkedOutCount++;
    else if (b.status === 'damaged') damagedCount++;
  }
  return {
    totalBooks: books.length,
    totalInventoryCost,
    totalAnnualRevenue,
    annualROI: Math.round((totalAnnualRevenue / totalInventoryCost) * 100),
    availableCount,
    checkedOutCount,
    damagedCount,
    utilization: Math.round((checkedOutCount / books.length) * 100)
  };
}

if (typeof window !== 'undefined') {
  window.CATALOGUE = CATALOGUE;
  window.ECON = ECON;
  window.bookEconomics = bookEconomics;
  window.catalogueMetrics = catalogueMetrics;
}
